'''
Author: yczheng-hit
Date: 2022-04-11 18:57:18
LastEditTime: 2022-04-13 11:32:13
LastEditors: Please set LastEditors
This script is used to generate hex file for 32bit-width memory.
Input file is generated by arm-none-eabi-objcopy
'''
#!/usr/bin/env python3

from sys import argv
import re
try:
    infile = argv[1]
    outfile = argv[2]
    print('\033[;34m-----Python Script generate.py is Running-----\033[0m')
    with open(infile, "r") as f:
        fileData = f.read()
    originData = re.split(r'@\w{8}',fileData)[1:]
    originAddr = re.findall(r"@\w{8}",fileData)
    sectionAddr = list()
    for i in originAddr:
        sectionAddr.append(int(i[1:],16))
    hexData = []
    for i in range(0,len(originData)):
        hexData.append([])
        hexData[i] = hexData[i] + re.split(r'[ \r\n]{1,3}',originData[i])
        hexData[i] = list(filter(None,hexData[i] ))

    assert len(hexData) == len(sectionAddr)
    byteLength=0
    with open(outfile,'w') as f:
        for i in range(0,len(sectionAddr)):
            while(byteLength<sectionAddr[i]):
                byteLength = byteLength+4
                f.write('00000000')
                f.write('\r\n')
            while(hexData[i]):
                tmp = hexData[i].pop(3)+hexData[i].pop(2)+hexData[i].pop(1)+hexData[i].pop(0)
                f.write(tmp)
                byteLength = byteLength+4
                f.write('\r\n')
    print("Data Length is",byteLength,"Bytes")
    print('\033[;32m-----Generate Hex SUCCESS!-----\033[0m')
except Exception as e:
    print('\033[;31m-----Generate Hex ERROR!-----\033[0m')
    print(e)
    print("Usage: python3 ./generate.py <inputfile> <outputfile>")
