set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN V20 [get_ports RSTn]
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property PACKAGE_PIN N20 [get_ports SWDIO]
set_property IOSTANDARD LVCMOS33 [get_ports SWDIO]
set_property PACKAGE_PIN M19 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SWCLK]
# set_property IOSTANDARD LVCMOS33 [get_ports miso]
# set_property IOSTANDARD LVCMOS33 [get_ports mosi]
# set_property IOSTANDARD LVCMOS33 [get_ports scs]
# set_property IOSTANDARD LVCMOS33 [get_ports sck]
# set_property PULLUP true [get_ports miso]
# set_property PACKAGE_PIN M20 [get_ports miso]
# set_property PACKAGE_PIN L17 [get_ports mosi]
# set_property PACKAGE_PIN L20 [get_ports scs]
# set_property PACKAGE_PIN M18 [get_ports sck]
set_property PACKAGE_PIN H16 [get_ports TXD]
set_property PACKAGE_PIN A20 [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports TXD]
set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property PACKAGE_PIN B20 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN B19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN D20 [get_ports {vga_data[6]}]
set_property PACKAGE_PIN D18 [get_ports {vga_data[7]}]
set_property PACKAGE_PIN H17 [get_ports {vga_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[8]}]
set_property PACKAGE_PIN D19 [get_ports {vga_data[5]}]
set_property PACKAGE_PIN H18 [get_ports {vga_data[4]}]
set_property PACKAGE_PIN E19 [get_ports {vga_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[3]}]
set_property PACKAGE_PIN F19 [get_ports {vga_data[0]}]
set_property PACKAGE_PIN K17 [get_ports {vga_data[1]}]
set_property PACKAGE_PIN F20 [get_ports {vga_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[2]}]
